### ISSUE TITLE
Open event Orga server generic installation on Mac OSX

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-server#3618]
**I'm submitting a ...**  (check one with "x")
- [x] feature request

**Current behavior:**
Currently, there is no documentation for OSX.

**Expected behavior:**
It'll be nice to have OSX documentation as well.

**Comment by parismita** [comment]
Hey @mahikaw can I work in this? I m new to the organization, can you please guide me on what to do?

**Comment by shubham-padia** [comment]
Please follow the local installation guide and if you find any steps
different on Mac OS, then add a seperate installation guide for the same.

On Dec 3, 2017 9:14 PM, "parismita" <notifications@github.com> wrote:

Hey @mahikaw <https://github.com/mahikaw> can I work in this? I m new to
the organization, can you please guide me on what to do?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fossasia/open-event-server/issues/3618#issuecomment-348786275>,
or mute the thread
