### ISSUE TITLE
Call for Speakers: After Speaker Information is saved screen should be returned to CfS with overlay

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#4491]
After speaker information is saved the user is firstly returned to the CfS page without overlay or secondly to the "MySessions" page.

Expected the user should be returned to the CfS page (screenshot below) to enter session information.

![screenshot from 2017-09-25 06-54-00](https://user-images.githubusercontent.com/1583873/30792945-95f6813a-a1be-11e7-989a-32ec3c0739e3.png)

**Comment by ananyo2012** [comment]
Working on this. Will respond when I come up with a solution.

**Comment by mariobehling** [comment]
@ananyo2012 Thanks for your improvements. The speaker form returns to the Call for Speakers page, but it does not show the popup. Expected: The speaker should be redirected to the Call for Speakers page with: The Popup open.

**Comment by ananyo2012** [comment]
@mariobehling Can re-verify it once again ?  I am returning a get parameter in [this line](https://github.com/fossasia/open-event-orga-server/pull/4493/files#diff-23af8900ed29426f5ab62f76117c2aabR508) so that `speaker-session-modal` pops up. Below is the attached screenshot of the same.
![image](https://user-images.githubusercontent.com/10486343/31849642-fcb4d666-b662-11e7-979d-24bf7d7caa62.png)
Note the url is `http://localhost:8001/e/58ed5b82/cfs/?show_speaker_modal=True` which contains a `show_speaker_modal` get parameter.

**Comment by shubham-padia** [comment]
@mariobehling Can you please recheck on this ?

**Comment by srv-twry** [comment]
Seems to be a v1 issue. Hence closing this. Please reopen if necessary.
