### ISSUE TITLE
Improve Call for Speakers Sign Up Process

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#4536]
The current process is:

* Go to 2018.fossasia.org (not fossasia.org)
* Click Speaker Registration
* Land at an information page
* Scroll to the bottom, click Submit Proposal
* Be told to log in or sign up
* Sign up
* Be dumped in the main page
* Find submission page somehow (perhaps by going back to the start of the process)
* Fill out form and press submit (I'm guessing, as the form can't even be accessed until all of the above has been completed).

A more sensible process is:

* Go to 2018.fossasia.org OR fossasia.org (there should be prominent, above-the-fold entry points on both pages)
* Click Speaker Registration
* Land at a page with explanatory information at the top, fields to fill in near the bottom, and a Submit button at the bottom.
* Fill in the fields and press Submit
* Receive a confirmation email

**Comment by rolandturner** [comment]
It occurs to me to add that we might wish to verify email addresses, so pressing the Submit button should present an explanatory message and the confirmation email should contain a confirmation link, the clicking of which puts the submission into the queue.

Behind the scenes, if this gets modelled as a user account with that email address, it is presumably important for the system to remember that the submitter:
- hasn't accepted terms of service; and
- hasn't set a password (so "login is impossible", not "login is with a blank password")
If this is what's happening in the database then it is presumably important to also remember that these two things haven't happened so that if the submitter later decides to create a user account with the same email address, they'll have to be taken through accepting terms and setting a password.

If abuse (particularly spam relaying) is a concern then it might make sense to include something like visualcaptcha, but this seems excessive. Bear in mind that one of the reasons for using EventYay submission instead of Google Forms is that, as we cater to both the Open Source community and the Free Software community, the latter object if we make them use a Google service merely to deal with us, meaning that using a Google CAPTCHA is probably inappropriate. If a CAPTCHA is used, it should be both open source and self-hosted.

**Comment by invinciblycool** [comment]
Claiming this.

**Comment by niranjan94** [comment]
@open-event-bot move to fossasia/open-event-legacy

**Comment by rolandturner** [comment]
Can someone explain, briefly, the reason for the move from open-event-server to open-event-legacy?
