### ISSUE TITLE
single track shows as required in event creation

### ISSUE THREAD

**Issue by eMBee** [fossasia/open-event-server#4626]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
creating any event defaults to having a main track and a microlocation (what's that, a room? :-)
then "track" shows up as a required selection in the cfs configuration.
incidentally, in the actual cfs no track is shown. so this is a cosmetic problem in the event creation only

**Expected behavior:**
it should be possible to remove any notion of track and room/microlocation alltogether, and not show track as required in the cfs creation form.

**Comment by srv-twry** [comment]
Tracks is required in the third step of the wizard. It can't be made optional. 
Tracks is required to have sessions -> sessions required to have speakers -> call for speakers needs speakers. So Track has to be compulsory in order to support Sessions and Speakers.
Similary a session needs a room/location. Hence atleast one has to be there. 
Closing this.
