### ISSUE TITLE
Add some sort of local Tester

### ISSUE THREAD

**Issue by Kreijstal** [fossasia/open-event-server#4744]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**

It's great that Travis-CI can always test the open-event-server from it's servers, but implementing it locally it's totally different and it might not work, because of conflicting versions, etc.

For example, deploying open-event server, right now it's extremely difficult but travis always says that there are no errors in it's development, could it be the specific version that travis is using, and couldn't we test it ourselves?
**Expected behavior:**

We can test the server ourselves locally, by making some sort of script that tests the code, installing whichever porgrams are needed. I think it would help many people understand the errors they're having plus we could make it easier to actually get the server up easily.

**Comment by schedutron** [comment]
We can test the code locally via `nosetests`, but why do we have to install the dependencies every single time?

**Comment by Kreijstal** [comment]
So we can deploy in presentations, new installations. And so beginners can start readily

**Comment by schedutron** [comment]
How do we plan to enable this? Via a shell script?

**Comment by iamareebjamal** [comment]
Travis is always checking the latest version of development branch 

Why deployment fail locally?

Travis had different `.env` This will hopefully be fixed and was reported earlier

Why tests fail locally?

Because travis has new db to work each time. This does not work correctly locally. Unfortunately, I haven't spent that amount of time on python to direct to correct usage. But in Java, we never let db be a part of unit tests, and for integration tests, we use in memory database H2. This is not possible in Python. But easier thing would be to use SQLite file database in tests. This will make it easy as pie to just test and delete the file. One more reason tests fail is because the test hooks are hardcoded Postgres commands, which may fail for a user without appropriate permissions. Fixing this behaviour will lock us in a wrong way of testing. So instead we should be fixing the way tests are setup

**Comment by iamareebjamal** [comment]
And about a script to handle running the server, I was already one which checks all dependencies and starts/installs missing ones like Redis, Celery and Postgres. I had to stop because of lack of time. I'll share redis shell script if someone wants to continue in the work

**Comment by schedutron** [comment]
@iamareebjamal Please share the script, I would like to work on it further.
🙂

**Comment by iamareebjamal** [comment]
https://gist.github.com/iamareebjamal/69711787848921eaea64d894089a22c5

**Comment by schedutron** [comment]
Do we have to migrate the entire test code involving DB from Postgres to SQLite?

**Comment by iamareebjamal** [comment]
No SQLAlchemy is ORM, works on both

**Comment by schedutron** [comment]
Cool, but there are certain sections which may be require changes. For example, 

https://github.com/fossasia/open-event-server/blob/43ffcb840d85d9024261a6d404f95237969abac9/tests/unittests/setup_database.py#L34

**Comment by iamareebjamal** [comment]
Yes definitely

**Comment by Kreijstal** [comment]
I believe nosetests does the job, however doesn't always pass, as it does in travis.
