### ISSUE TITLE
Integrate Elastic search

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-server#4875]
**Is your feature request related to a problem? Please describe.**

Integration of Elastic search is important to get closer to a release state. 

- [ ] Check if it is already implemented. If yes, then test it and fix bugs if any.
- [ ] If not implemented, then please implement.

**Comment by maxlorenz** [comment]
What is the scope of this issue? This needs a list of data that ES should hold, when to update etc.

**Comment by srv-twry** [comment]
Yes, I am yet to dig into this issue. I have created this issue because a lot of the developers aren't sure about the missing features. I haven't claimed this. Whoever claims this should do the research and then implement it accordingly.

**Comment by maxlorenz** [comment]
@srv-twry I implemented ES for events. It syncs and has an search endpoint that does fuzzy matching

**Comment by maxlorenz** [comment]
Follow-up: Integrating ES was not too hard - but adding it to the filter implementation is. Every `ResourceList` that is used for interfacing the REST api has a `data_layer` member that is a dict containing the class to inherit from (example from `EventList`):

```python
    data_layer = {'session': db.session,
                  'model': Event,
                  'class': SearchFilterLayer,
                  'methods': {'after_create_object': after_create_object,
                              'query': query
                              }}
```

This is important because the `SearchFilterLayer` has access to the `query` object that is used to interface `SQLAlchemy` here and `SQLAlchemy` then uses the `Event` model to access the data (members). ES however uses a different data class that the `SearchFilterLayer` has no direct access to as the `EventList` is not accessible there. Within the `EventList` I could add the ES integration and convert `Event` queries to ES queries and combine results etc *but* the `SearchFilterLayer` has a 'hidden instantiation' that I don't have control over and that I would have to add a reference to the ES data class to. Removing certain filters and replacing them with the ES query results works in the `EventList` class but ignores the `and` and `or` operators present in the filters. How to proceed here?
