### ISSUE TITLE
Add deleted_at field to every user & event related model and schema

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-server#4879]
**Is your feature request related to a problem? Please describe.**

Since we are using soft deletion by default, we should add field `deleted_at` to all the schemas and models which are directly related to event or user.

**Describe the solution you'd like**

Each and every resource that supports deletion should have a delete_at field. 

**Additional context**

Required to fix #4874 

CC: @niranjan94 @shubham-padia @SaptakS

**Comment by shubham-padia** [comment]
I don't think deleted_at should be added to every model. It should be added only wherever soft deletion is required.

**Comment by srv-twry** [comment]
thank you, but what is the criteria on which we decide whether soft deletion is required or not ?

**Comment by shubham-padia** [comment]
Anything that maybe useful to restore later can have a deleted_at column, e.g events, sessions, etc. It does not make sense to add soft-deletion to e.g custom forms, sponsors, notification, etc. `deleted_at` should be added very carefully and only to those tables which have the highest need of a restore. Increasing the models with `deleted_at` will result in a drastic increase in the database entries due to useless soft-deleted entities. I think no change should be made at this moment to add soft deletion to any others than the existing ones. Soft-deletion capability should only be added based on user feedback once the app is in production.

**Comment by srv-twry** [comment]
Alright, thank you :)
closing this

**Comment by srv-twry** [comment]
Reopened issue based on the suggestions by @niranjan94 in the channel

> any model and its related models that can be deleted by the user would need soft deletes.
So, basically event model + all its related resources.
user model and and all of user's related resources.
see ... for example, sponsors is directly related to an event.
If a user deletes an event, sponsors should also be deleted. And when the user restores the event, sponsors should also be restored.
It doesn't make sense to just restore the event and end up losing everything else does it.
