### ISSUE TITLE
"Deploy to Heroku" button not working

### ISSUE THREAD

**Issue by Saurabh3333** [fossasia/open-event-server#4893]
**Describe the bug**
The `Deploy yo Heroku` button not working at [Link](https://github.com/fossasia/open-event-server/blob/development/docs/installation/heroku.md) since it is unable to find `app.json` file.

**Additional details (please complete the following information):**
 - OS: Ubuntu

**Comment by srv-twry** [comment]
@Saurabh3333 Please fix it. 
We initially had a combined server and frontend repository i.e. both the server and frontend was coupled. It is called version 1 of open event
Now we have separate frontend and server repos as you can see and this is the v2. 
This bug is because it deploy to heroku button was setup for v1 but wasn't updated after moving to v2. Hence it expects app.json but it isn't available now in the repository.
