### ISSUE TITLE
Reset password feature isn't sending any email

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-server#4910]
**Describe the bug**
The endpoint `open-event-api-dev.herokuapp.com/v1/auth/reset-password` isn't working. Even though it shows "Email Sent"

**To Reproduce**
1. Try sending a POST request to `open-event-api-dev.herokuapp.com/v1/auth/reset-password`.
2. Open the email account, for the email address which was used in the body.

**Expected behavior**
A mail with a token should be sent.

**Additional context**
![screenshot from 2018-06-15 14-18-58](https://user-images.githubusercontent.com/35009811/41459538-7f3f982e-70a7-11e8-92b7-9a34a9253506.png)

**Comment by schedutron** [comment]
Which email id is used to send this mail?

**Comment by CosmicCoder96** [comment]
@schedutron Any updates ? It was working fine around 2 weeks ago. Now the mails are not getting sent. Checked the spam folder as well.

**Comment by schedutron** [comment]
I checked the Heroku logs, and it's throwing `Sendgrid key not defined` error, so I need to define a Sendgrid key in Heroku's settings in its Postgres DB.

**Comment by schedutron** [comment]
So what should I do - create a dummy email, create it's Sendgrid API key and post it to Heroku's settings? Or re-create the key for the existing email that is used?

**Comment by schedutron** [comment]
Heroku wasn't logging useful information because exceptions were getting contained in the wrong manner, e.g, even if the `email_from` key was not defined, no error was raised. There were multiple keys undefined in Heroku settings, but I have fixed them now.

@srv-twry @mishuvs @CosmicCoder96 can you please confirm that email endpoints are working for you? I'll add proper exceptional handling by creating a different relevant issue and PR.

**Comment by schedutron** [comment]
Heroku wasn't logging useful information because exceptions were getting contained in the wrong manner, e.g, even if the `email_from` key was not defined, no error was raised. There were multiple keys undefined in Heroku settings, but I have fixed them now.

@srv-twry @mishuvs @CosmicCoder96 can you please confirm that email endpoints are working for you? I'll add proper exceptional handling by creating a different relevant issue and PR.

**Comment by mishuvs** [comment]
@schedutron I tried the same as in the screenshot above, again, but it didn't work. The response shows "Email Sent" but I can't find any email received. So it seems to be not working for me. @schedutron Is it working for you?

**Comment by mishuvs** [comment]
@schedutron I tried the same as in the screenshot above, again, but it didn't work. The response shows "Email Sent" but I can't find any email received. So it seems to be not working for me. Is it working for you?

**Comment by schedutron** [comment]
@mishuvs Did you check in spam folder? It might go there, because initially I received the email in spam.

**Comment by mishuvs** [comment]
Got it! But the sender email is being shown as `open_event_test_user@fossasia.org`. Shouldn't it be an eventyay email address?

**Comment by srv-twry** [comment]
@mishuvs Why ? You are using the development branch deployment. Not the production one.

**Comment by mishuvs** [comment]
Also, one more thing: I am getting this on clicking a reset password link I just received. Is it working for you?

![screenshot from 2018-07-15 18-03-23](https://user-images.githubusercontent.com/35009811/42733987-7dda02c0-8859-11e8-82fa-850f1ddc6533.png)

**Comment by schedutron** [comment]
I have reconfigured Heroku dev server settings for front-end url, still 404 persists.
