### ISSUE TITLE
Allow checking whether an email is registered

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-server#4939]
**Is your feature request related to a problem? Please describe.**

Users API should allow checking whether an email is registered.

**Describe the solution you'd like**

A POST request requiring only an email address should respond whether the email is registered or not.

**Additional context**

Orga App issue: [#971](https://github.com/fossasia/open-event-orga-app/issues/971)

**Comment by Kreijstal** [comment]
The user api schema has already an attribute called  `"is-verified"` this is essentially what you're looking for.

![image](https://user-images.githubusercontent.com/2415206/42131259-a2db503a-7cfe-11e8-916a-f44f70916615.png)

**Comment by mayank8318** [comment]
@Kreijstal No, what he is saying is an endpoint to check if that particular email-id is already registered or not. Just as the username is checked for availability when you type it on other websites.

**Comment by Kreijstal** [comment]
ah, e-mail in open-event is already unique so the server won't allow it to register to more than user, because in open-event there are no usernames, I'd say that's a frontend issue.

**Comment by srv-twry** [comment]
> GET /v1/users?filter=[{"name":"email","op":"eq","val":(value of the e-mail address you want to check)}]

This will require admin access. How will the FE/Android app use it ?
@Kreijstal

**Comment by srv-twry** [comment]
See probably you guys are not familiar with the requirement. This is a requirement in the orga app. 
What we want to do in the app is that when the user opens the app, he/she will be presented with a screen asking for the email address. Now the app will check if the email is registered or not.
 
1. If registered, then we will present the user with a password field
2. If not registered, then the user will be asked to register.

When no one has logged in,we cannot use /v1/users since it requires admin access. We have to make this endpoint public i.e. it shouldn't even require a JWT token just like the endpoint for registering the user. Create a new endpoint for this which accepts the email and sends the response as verified or not. 

@mayank8318 @Kreijstal

**Comment by mayank8318** [comment]
Ok I will work on this
