### ISSUE TITLE
Add top bar for user to agree to cookie policy

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#5068]
Most website nowadays require information about stored data and cookies. Please also add this info to the system as below. Please compare how Eventbrite implements it.

> This website, and certain approved third parties, use functional, analytical and tracking cookies (or similar technologies) to understand your event preferences and provide you with a customized experience. By closing this banner or by continuing to use the site, you agree. For more information please review our cookie policy.

![screenshot from 2018-07-11 01-19-20](https://user-images.githubusercontent.com/1583873/42542774-b3a6e710-84a8-11e8-946a-836f76e94d30.png)

**Comment by srv-twry** [comment]
@mayank8318 Looking into this issue in detail, I found that we don't need that column for cookie policy in the user model. Users don't have to explicitly approve it. They are approving it just by using the site. 
The requirement of this issue is that we should allow the admin of the system to add this information to the site. Also add a default cookie policy with the message that @mariobehling has mentioned. 
Please revert your PR and simply add a cookie-policy in the settings column.

**Comment by srv-twry** [comment]
Closing now. Implemented.
