### ISSUE TITLE
Add third party authentication from google

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-server#5153]
**Is your feature request related to a problem? Please describe.**

We have already implemented third party auth using facebook. Now we should do the same for google.

**Additional context**

Parent: #5115

**Comment by starlord1311** [comment]
hasnt it been already done at the place where fb auth has been done?

**Comment by srv-twry** [comment]
@bhaveshAn Could you please guide @starlord1311 here ?

**Comment by bhaveshAn** [comment]
> hasnt it been already done at the place where fb auth has been done?

@starlord1311 In FB PR the redirect url part was done for all the social logins but we need implementation for accessing the access token and token type by individual PRs.

**Comment by starlord1311** [comment]
@bhaveshAn i didnt get you. can you please explain?

**Comment by srv-twry** [comment]
@starlord1311 Can you please check the channel. I'll help you there.

**Comment by Akhelesh** [comment]
The issue has been inactive for a long time. I am taking it up

**Comment by iamareebjamal** [comment]
@Hudda I don't see it mentioned anywhere that you were working on it

**Comment by Hudda** [comment]
@iamareebjamal sorry, my mistake. I started working on this but didn't mention it anywhere.

**Comment by Akhelesh** [comment]
@Hudda It's not appropriate to not mention that you are working on an issue or else it creates such problems. Besides I too have come up with the solution and would not like my effort to be wasted but I am willing to step down since you started early, if you can open the PR within a day(since you completed it mostly). I will open the PR if that is not the case.
Be sure to comment on the issue in the future, if you take up an issue to avoid such scenarios.

**Comment by Hudda** [comment]
@Akhelesh thanks brother.

**Comment by mariobehling** [comment]
Priority low: Delay
