### ISSUE TITLE
Sessions can have the date in the past

### ISSUE THREAD

**Issue by Haider8** [fossasia/open-event-server#5670]
**Describe the bug**
Currently a session can be held in the past date which is not correct.

**To Reproduce**
1. Go to 'create event' or 'edit event' on the Manage Events section
2. Click on 'Sessions and Speakers' tab
3. After filling mandatory fields input 'Starts' or 'Ends' field in the past

**Expected behavior**
Should have rejected the past dates.

**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS]

**Additional context**
Working on it

**Comment by iamareebjamal** [comment]
Yes there may be many more logical errors but there are much more higher priority tasks than this. You may work on this but try to take up tasks which block the API from being used bug free. These issues can be categorized as enhancements and taken up later when breaking bugs are solved. However since you have worked recently on a similar issue, go ahead

**Comment by Haider8** [comment]
@iamareebjamal will work on high priority issues.

**Comment by kushthedude** [comment]
@Haider8 I think its same as #5663

**Comment by iamareebjamal** [comment]
No, it's not
