### ISSUE TITLE
The ability to delete my account.

### ISSUE THREAD

**Issue by ghost** [fossasia/open-event-server#5805]
**Is your feature request related to a problem? Please describe.**
I had this app mistaken for something else, and I would like to delete my account. However, there doesn't seem to be an easy way to do that, and the only way to contact you according to your website (aside from social media, which I don't have) is Github.

**Describe the solution you'd like**

Allow somebody to erase their account via a button on their Profile. Or better yet, just delete my account so I can forget about this already.

**Describe alternatives you've considered**
I don't know what else to do, this seems like a very basic function for an app to have.

**Additional context**

Thank you.

**Comment by shreyanshdwivedi** [comment]
I'll take a look to it. @iamareebjamal @CosmicCoder96 I think this should be implemented. Your views?

**Comment by mrsaicharan1** [comment]
If this is to be implemented, I would like to work in collaboration with
you. I could implement the front-end part of this @shreyanshdwivedi.

**Comment by iamareebjamal** [comment]
Due to the nature of the application, it is not very simple to do so.

Consider this - 

I publish an event, add paid tickets, people buy them.
I get 1000s of dollars in my account, and then just delete my account. No event happens, people have encountered a fraud and it has been done through our system. 

It is definitely possible to add this feature, but it has several aspects of security and real life, and hence needs to be discussed and planned thoroughly before implementing.

Similarly, deleting of an event should be prevent by an API if any order has been placed for the event, and so on

**Comment by shreyanshdwivedi** [comment]
@iamareebjamal I think we can implement this feature to the users who have not created any event. I don't think there is any other possibility of fraud other that the one you stated, which can be eliminated if we apply a check on which I stated above.
Also, currently any event can be deleted easily. Shoul I open an issue to apply a check which prevents deleting an event which has any order associated with it?

**Comment by iamareebjamal** [comment]
Yes, that's what I meant

**Comment by kushthedude** [comment]
@shreyanshdwivedi , Implementing the feature on user who have not created any event should also be considered , If a user has bought some amount of Free Tickets for spamming and user deletes his account , It can be a loss to event organiser . So this needs a proper discussion .

**Comment by shreyanshdwivedi** [comment]
@iamareebjamal @mrsaicharan1 @kushthedude  I think it's time that we should finalize what needs to be done for this issue. I'm suggesting that for initials we can allow someone who have not created any event or is not associated with any order to delete his/her account. Your views?

**Comment by iamareebjamal** [comment]
Yeah, go ahead
