### ISSUE TITLE
Deleted user cannot signup with the same email

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-server#5889]
**Describe the bug**

Once a user gets deleted by admin or if he himself deletes the account, then later he cannot signup with the same email. An error `User already exists.` persists

**To Reproduce**
1. Go to `Admin > Users`
2. Delete a test user
3. Try to signup again using same email as of test user

**Expected behavior**

The user must be allowed to signup with that email

**Additional context**

Related to https://github.com/fossasia/open-event-server/issues/5805
Will work on it

**Comment by kushthedude** [comment]
@shreyanshdwivedi is the user able to login with the following credentials

**Comment by shreyanshdwivedi** [comment]
Nope. When you try to login using the old creds, it raises error `Your credentials were incorrect.`

**Comment by iamareebjamal** [comment]
Yeah. When deleting a user, append an underscore in their email, and keep appending until it is unique

**Comment by iamareebjamal** [comment]
Also create a migration to do the same to previously deleted users

**Comment by uds5501** [comment]
@shreyanshdwivedi let me know if you need any help regarding this?

**Comment by shreyanshdwivedi** [comment]
@iamareebjamal you mean when deleting a user on server using this code  -
```
user.deleted_at = data.get('deleted_at)
```
I should also update email of the user like this -
```
user.email = '_' + user.email  #till it becomes unique
user.deleted_at = data.get('deleted_at)
```
Right?

**Comment by iamareebjamal** [comment]
```user.email = user.email + '_' ```

Yes

**Comment by shreyanshdwivedi** [comment]
@uds5501 @iamareebjamal I've a query regarding this. Suppose I updated the email of user by apapending `_` to his/her email when admin deleted his/her account. 
Now comes the real problem -
 - When admin views his/her deleted users list, the email will be the new appended email. However when I add this code block -
```
if has_access('is_admin') and data.get('deleted_at') != user.deleted_at:
            notUniqueEmail = 1
            userEmail = user.email
            while notUniqueEmail:
                print(userEmail)
                try:
                    db.session.query(User).filter_by(email=userEmail).one()
                except NoResultFound:
                    user.email = userEmail
                    notUniqueEmail = 0
                else:
                    userEmail = userEmail + '_'
            user.deleted_at = data.get('deleted_at')
```
the deleted users list produces this error `TypeError: list indices must be integers or slices, not str`.

 - The second issue. If admin deleted a user and now user signs up with same email and admin deletes this user too, we have two entries for same user. And admin can restore both the users, this will be really bad experience bcoz it'll definitely create a number of issues with it.

Your views?

**Comment by kushthedude** [comment]
@shreyanshdwivedk I was thinking about the same issue , as the deleted
users still have their data stored stored in database which can be restored
by superadmin , we can have two approaches here -:
1.) Erase the user data from database .
2.) Do something like facebook , if a deleted user sign in again , restore
his data except events and orders .
Your views @uds5501 , @iamareebjamal

**Comment by kushthedude** [comment]
> @uds5501 @iamareebjamal I've a query regarding this. Suppose I updated the email of user by apapending `_` to his/her email when admin deleted his/her account.
> Now comes the real problem -
> 
> * When admin views his/her deleted users list, the email will be the new appended email. However when I add this code block -
> 
> ```python
> if has_access('is_admin') and data.get('deleted_at') != user.deleted_at:
>             notUniqueEmail = 1
>             userEmail = user.email
>             while notUniqueEmail:
>                 print(userEmail)
>                 try:
>                     db.session.query(User).filter_by(email=userEmail).one()
>                 except NoResultFound:
>                     user.email = userEmail
>                     notUniqueEmail = 0
>                 else:
>                     userEmail = userEmail + '_'
>             user.deleted_at = data.get('deleted_at')
> ```
> 
> the deleted users list produces this error `TypeError: list indices must be integers or slices, not str`.
> 
> * The second issue. If admin deleted a user and now user signs up with same email and admin deletes this user too, we have two entries for same user. And admin can restore both the users, this will be really bad experience bcoz it'll definitely create a number of issues with it.
> 
> Your views?

The error here created is due to the email now created after is not a form of unicode email which has been recently solved by @CosmicCoder96 in frontend

**Comment by uds5501** [comment]
@shreyanshdwivedi Or we could simply not use SoftDeletionSchema for this? But that would finish the restoration feature.

I like @kushthedude idea. We can see the last login / deleted-at timestamp and simply login the same user all over again if it's less than 15 days Otherwise, reallocate the same user entry to the new user except, with the user centric data wiped out and a password reset link being sent to the user.

@iamareebjamal @mariobehling Please see this.

**Comment by iamareebjamal** [comment]
I don't understand what's so complicated here that this much of analysis is required. We want the email field to be unique, none of the above solutions work with that. How can you have a unique field with duplicate emails? Also, restoration will and should not work in case someone has created a new account with that email. 

> When admin views his/her deleted users list, the email will be the new appended email

As it should be

> Erase the user data from database .

No

> Do something like facebook , if a deleted user sign in again , restore
his data except events and orders .

We don't want the deleted user to sign in. We want it to sign up. Which will not be possible because unique key constraint will prevent that from creating an account, and we don't want this much complication where we restore an account to someone else. Where will we keep the previous data? How will we verify that it is the same person who deleted the account? 


> And admin can restore both the users

Restoring will be a very rare manual process, and you can't still have 2 users with same email because of unique contraint, that's why we want to keep it and that's why we are appending _ to its end. This will not be a problem ever. For one email, tere can be infinite deleted users, but only one active. Same as happens with twitter. You can change you username and other person can take that username and repeat

**Comment by uds5501** [comment]
@iamareebjamal @shreyanshdwivedi Apparently, adding an `_` at the end won't be of much help. How about instead of 
`xyz@email.com` to `xyz@email.com_`, we do `xyz_@email.com`

The former one gives a unicode violation and hence this page :
![image](https://user-images.githubusercontent.com/21087061/57912314-a71bcf80-78a7-11e9-92ed-c617a4fb53d1.png)

**Comment by shreyanshdwivedi** [comment]
>the deleted users list produces this error TypeError: list indices must be integers or slices, not str.

uds5501 exactly. Even I mentioned it earlier. Besides the error u mentioned, the list page is also breaking.

>How about instead of
xyz@email.com to xyz@email.com_, we do xyz_@email.com

iamareebjamal your thoughts?

**Comment by CosmicCoder96** [comment]
@uds5501 it is more likely a violation of the field of type ‘email’. It
might not be a valid email address according to marshmallow validations
defined in user schema. Not a Unicode issue. Xyz_@email.com if allowed
sounds good.

**Comment by uds5501** [comment]
@CosmicCoder96 I have checked, the XYz_ works fine and yes, it's a schema validation issue.

**Comment by shreyanshdwivedi** [comment]
It can be worked only after https://github.com/fossasia/open-event-server/pull/5882 gets merged.

**Comment by iamareebjamal** [comment]
`xyz_@email.com` is a problem. Now we taking up a new email which may belong to other person

Try `xyz@email.com.deleted`

**Comment by uds5501** [comment]
@iamareebjamal `.deleted` works 
@shreyanshdwivedi apply these changes in the migration?

**Comment by shreyanshdwivedi** [comment]
Yeah, once the mentioned PR gets merged, I'll pish the changes alongwith a migration file to update the email of deleted users.
