### ISSUE TITLE
Invoice cant render currency symbol

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-server#6018]
#### Details :

- Invoice generated after buying ticket is not rendering `Currency Symbol` and showing a black dot instead

#### Screenshot

<img width="1440" alt="Screenshot 2019-06-09 at 5 30 12 PM" src="https://user-images.githubusercontent.com/44091822/59158742-7876ca80-8adc-11e9-8fa6-8a8a5b2d2ba7.png">

**Comment by kushthedude** [comment]
@mrsaicharan1 Can you please have look into it

**Comment by mrsaicharan1** [comment]
@kushthedude Which currency symbol were you using?

**Comment by kushthedude** [comment]
INR

**Comment by mrsaicharan1** [comment]
@kushthedude Why is the order invoice on the pending page? There should never be an order invoice for a pending order.

**Comment by kushthedude** [comment]
> @kushthedude Why is the order invoice on the pending page? There should never be an order invoice for a pending order.

That's an order invoice of `Placed Order`, And there should be an invoice of `Offline Order`

**Comment by mrsaicharan1** [comment]
This is happening for quite a few currency symbols. I've explored what was going wrong and found out that `pisa`, the library which is currently being used to generate invoice pdfs is not able to render these symbols properly. For a workaround, to display what currency is present, I was thinking of removing the template filter which is being used so that it would display `INR`,'THB'   in the order invoice. Is that okay @iamareebjamal @shreyanshdwivedi @uds5501 ?

**Comment by uds5501** [comment]
@mrsaicharan1 I think it will be fine to work that way.

**Comment by iamareebjamal** [comment]
Try some solutions here https://duckduckgo.com/?q=pisa+python+unicode&t=canonical&ia=web

**Comment by mrsaicharan1** [comment]
@iamareebjamal, tried out some solutions before, will try these out too and
get back to you.

**Comment by mrsaicharan1** [comment]
@iamareebjamal I've tried the solutions but alas, the black dot icon still remains. :/

**Comment by iamareebjamal** [comment]
OK, go ahead with what was planned
