### ISSUE TITLE
Implementation ReCaptcha for Sensitive Activities

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-server#6036]
Please See https://github.com/fossasia/open-event-frontend/issues/3129

**Comment by kushthedude** [comment]
@uds5501 Would you like to take server side ?

**Comment by kushthedude** [comment]
@iamareebjamal Can you please help, How do I integrate the following reCAPTCHA with server, I already read docs of ember-g-reCAPTCHA, didn't find much about server integration, And after reading the integration of reCAPTCHA with flask, They provide the method to integrate with WTForms and we are not using WTF anywhere except for login validators.

**Comment by iamareebjamal** [comment]
https://codelabs.developers.google.com/codelabs/reCAPTCHA/index.html#6

**Comment by mrsaicharan1** [comment]
@uds5501 Would you like to take this up?

**Comment by kushthedude** [comment]
Yeah it would be great if someone could help with Server side , I have
already done the FE using ember g captcha on the local

**Comment by uds5501** [comment]
@kushthedude I don't think ember g captcha is gonna cut it. 
Please take a look at the link @iamareebjamal  provided and check if we can merge the steps given in this resource.

**Comment by kushthedude** [comment]
@uds5501 Implementing manual scripts on FE as done for omise will break our
structure of code, I will strongly suggest to use some already developed
module or package, manually implementing reCAPTCHA would take time.

**Comment by iamareebjamal** [comment]
@kushthedude What manual scripts? This is the way captcha is implemented everywhere. Either find a way ember captcha works with backend integration, or find an ember package that does, or write your own. Writing vanilla javascript is bad, since when? If you only want to use ember package, and there is no such package available, write one yourself. 

All these packages are written by humans only and in vanilla javascript. They are not forged by magic.

Also, heavily relying on frameworks have only hurt our flow, not improved it. Trust me. Flask was used in backend to be flexible for us to do what we wanted even if a package wasn't available for it, because it was a microframework. A lot of functionality implemented in our backend has been written by ourselves and later replaced with packages when they were at par with our specification. This would not be possible for frameworks like Django as they take away control from your hand.

Ember in frontend has been completely opposite choice to flask. It is more than Django of backend because the choice of ember in FE has influenced the implementation of backend. Where for using ember data, we used JSONAPI spec, but no developer implements new endpoints using it correctly. Similarly, OAuth and Payment integrations are so tightly coupled with ember that they are unusable in mobile and hence, there is a need to implement duplicate endpoints each for mobile and FE. So, it has made it easy for FE, but harder for server and mobile. 

There needs to be a single implementation in backend which both mobile and FE can use. It may mean there is no compatible package in ember for that, so let's write a custom one as server and mobile already do. Or find one which can work in a compatible flow with mobile and server

**Comment by iamareebjamal** [comment]
And you think manually implementing captcha will take time as you have to implement the whole captcha recognition system yourself. We have to literally use a library Google provides and hence has already made the process extremely easy. Let's not be spoilt developers who can only add a feature if there's a package for it

**Comment by mariobehling** [comment]
There are already some Captcha areas and we will re-approach this question when we move to the next version with React. Therefore closing this.
