### ISSUE TITLE
Mails with attachment are blocked by gmail

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#6047]
![image](https://user-images.githubusercontent.com/17252805/59480039-a750c000-8e91-11e9-8698-ae52d3420cce.png)

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 Is this only through Sendgrid or protocol agnostic?

**Comment by CosmicCoder96** [comment]
Sendgrid, I believe merely notified that mail is blocked. The mail was
actually blocked by gmail itself.

**Comment by iamareebjamal** [comment]
Thus, it is protocol agnostic

**Comment by mrsaicharan1** [comment]
@iamareebjamal @CosmicCoder96 There's supposed to be an option which needs to be enabled. It's called `Less Secure Apps` in Gmail. Attachments are usually blocked because of that.
![Screenshot 2019-06-15 at 2 02 14 PM](https://user-images.githubusercontent.com/25197147/59549100-3097ed80-8f8b-11e9-924d-b5bea9a046f9.png)

**Comment by CosmicCoder96** [comment]
Able to receive mails in latest testing.
