### ISSUE TITLE
Internal server error during email verification

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-server#6167]
Error when a wrong token is used for email verification.

POST `/v1/auth/verify-email`
```
{
  "data": {
    "token": "your token"
  }
}
```

Response for `https://open-event-api-dev.herokuapp.com`:
```
<html>
    <head>
        <title>Internal Server Error</title>
    </head>
    <body>
        <h1>
            <p>Internal Server Error</p>
        </h1>
    </body>
</html>
```

Response for `https://api.eventyay.com`:
```
{
    "errors": [
        {
            "detail": "Unknown error",
            "source": {
                "pointer": ""
            },
            "status": 500,
            "title": "Unknown error"
        }
    ],
    "jsonapi": {
        "version": "1.0"
    }
}
```

**Comment by iamareebjamal** [comment]
This is on dev server? Please post complete URL and payload. How else will we reproduce the error?

**Comment by ShridharGoel** [comment]
Updated.

**Comment by mrsaicharan1** [comment]
I'd like to work on this.
For now, I've tried reproducing it locally and it's the `binascii` error.
`binascii.Error: Incorrect padding` 
Usually, this error occurs when the length of the base64 encoded string is not divisible by 4. We usually add padding by appending `==` or `====` to enable divisibility by 4.
But the problem is that the encoded string's length is 168. Any pointers on this? @shreyanshdwivedi @uds5501 ?

**Comment by iamareebjamal** [comment]
Any invalid base64 string throws this exception, it should be handled and response sent that it is an invalid token

**Comment by prateekj117** [comment]
@mrsaicharan1 May I take this one?
