### ISSUE TITLE
API implementation for Token Refresh

### ISSUE THREAD

**Issue by James7777** [fossasia/open-event-server#6168]
**Is your feature request related to a problem? Please describe.**

There is currently an issue in both apps(attendee and organizer) when the token expires, the user is asked to re-login, this is not good for user experience. 

**Describe the solution you'd like**

Token refresh should happen under the hood using the existing expired token.

**Describe alternatives you've considered**

Two options;
- automatically refreshing token using a background service like WorkManager 
- automatically using authenticator to capture 401 errors, refresh token synchronously and retry failed requests.

**Additional context**

**Comment by iamareebjamal** [comment]
For server, it doesn't matter the approach client takes. That detail is to be discussed on client repo. For now, long life refresh tokens are to be granted if the request payload contains `remember-me` as true. If the client is mobile, it'll be granted the refresh token in response JSON itself. In case of web, it'll be sent using HttpOnly and secure cookie to protect from XSS attacks. This will still be vulnerable to CSRF attacks, so need to think about how to handle that on web. Maybe API based CSRF token, but I don't know how feasible that will be. But can still be first implemented for mobile.

An endpoint for refreshing the token is to be implemented. Which will accept the refresh token either from JSON or cookie. 

An endpoint for blacklisting refresh tokens is to be implemented in order for a user to restrict login from leaked tokens. We'll not store the blacklisted tokens, but simply add a one to one mapping of user to blacklist-time when user asks to blacklist the tokens. Any refresh token or auth token created before that time will be considered invalid. And thus user will be logged out of all the previous devices as well. This will act as a double security feature, by limiting the attack due to leaked credentials and also logging out the user from all persistent sessions.

**Comment by James7777** [comment]
Sounds like a good plan, thanks iamareebjamal

**Comment by iamareebjamal** [comment]
Will be done within fortnight hopefully

**Comment by James7777** [comment]
Thank you so much guys for this project

**Comment by ashutosh1919** [comment]
@James7777 and @iamareebjamal, I want to work on this issue, Please assign me the task. I will do it within 3 days.

**Comment by James7777** [comment]
Hi,
Unfortunately I cant assign issues.
Thanks
Caleb
