### ISSUE TITLE
Ticket PDF not found while sending emails

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6383]
https://sentry.io/share/issue/5257703ed89345b3abf0b2432765f4ae/

**Comment by mrsaicharan1** [comment]
@iamareebjamal #6331 This PR should've fixed that. Is this happening on the dev server or production?

**Comment by iamareebjamal** [comment]
Alright. This was production

**Comment by iamareebjamal** [comment]
https://sentry.io/share/issue/fdf7fc78bcdf45f4b5baad6454a6a9f1/
https://sentry.io/share/issue/a19b0ddffd644211a714b612c6b4ff9b/

These will be fixed by it as well, right?

**Comment by mrsaicharan1** [comment]
@iamareebjamal These weren't related to that tickets URL path fix so these might persist. I will check right now and get back to you here.

**Comment by iamareebjamal** [comment]
FileNotFound - 'attachments': ['generated/tickets/attendees/ticke...","id":"c4a1ef4d-54f6-4392-afd4-da91f181f815","exc":"FileNotFoundError(2, 'No such file or directory')"}

'attachments': ['generated/tickets/attendees/ticke...","id":"c4a1ef4d-54f6-4392-afd4-da91f181f815","exc":"FileNotFoundError(2, 'No such file or directory')"}

**Comment by mrsaicharan1** [comment]
@iamareebjamal Okay looking at the attachment paths, yes they would be fixed. These would be fixed as well.
Also, 'ticket_attendee': 'attendees/tickets/pdf/{identifier}' can be safely removed from storage helpers as we've moved to 'tickets_all': `generated/orders/tickets/pdf/...` so that co-organizers, organizers and attendees could download the tickets.

**Comment by iamareebjamal** [comment]
OK, open an issue to remove this
