### ISSUE TITLE
Switch tests to py.test from nose

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6503]
nose is unmaintained and recommends to use nose2, unittest or pytest

pytest has fixture based dependency injection, and parametrization, and is generally better

**Comment by TJBANEY** [comment]
Tests you say? I'd be happy to take this on for you 💪

**Comment by souravsingh** [comment]
Made a PR at #6507. Please provide feedback.

**Comment by iamareebjamal** [comment]
@TJBANEY mentioned to work on it first. Also, this issue was not going to get solved by changing a line in requirements.txt

If it would be, we wouldn't have opened an issue for it, just did it ourselves

**Comment by souravsingh** [comment]
My bad. I forgot to add the commits to test files

**Comment by kushthedude** [comment]
> My bad. I forgot to add the commits to test files

Did you just ignore my comments and @iamareebjamal  comment on your PR and the following issue?
@souravsingh We follow a proper development workflow here at FOSSASIA and you just created a vague PR before dropping comment and also not to mention that change was of one line.

**Comment by iamareebjamal** [comment]
Please let @TJBANEY work on it as he commented first. If he has not worked on it for a week, you can proceed. We follow rules and ethic here

**Comment by souravsingh** [comment]
@kushthedude I had forgotten to add the commits for test files, which I added later(which you didn't care to see). And I worked on the issue, since the issue doesn't have any assignee. I apologize if this inconvenienced you.

**Comment by iamareebjamal** [comment]
We don't add assignees here. Please read the guidelines. We can't accept your PR unless @TJBANEY agrees to it or does not send a PR within a week.

**Comment by TJBANEY** [comment]
@iamareebjamal  @souravsingh This is fine, It was late in my timezone when I started on it, so I didn't get much headway on it anyway 🙂

**Comment by amansheaven** [comment]
Can I pick up on this? @iamareebjamal

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by amansheaven** [comment]
Sorry for late response but I was successful in setting up the server, I tried running nosetests but they seem to be unsuccessful. Screenshot is attached for the same, 

Stack :
======================================================================
ERROR: Test generation of hash for a key.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aman/open-event-server/tests/all/unit/api/helpers/test_storage.py", line 53, in test_generate_hash
    with patch('app.api.helpers.storage.get_settings') as get_settings:
  File "/usr/lib/python3.6/unittest/mock.py", line 1231, in __enter__
    self.target = self.getter()
  File "/usr/lib/python3.6/unittest/mock.py", line 1401, in <lambda>
    getter = lambda: _importer(target)
  File "/usr/lib/python3.6/unittest/mock.py", line 1084, in _importer
    thing = __import__(import_path)
  File "/home/aman/open-event-server/app/__init__.py", line 41, in <module>
    from app.api.helpers.scheduled_jobs import send_after_event_mail, send_event_fee_notification, \
  File "/home/aman/open-event-server/app/api/helpers/scheduled_jobs.py", line 12, in <module>
    from app.api.helpers.query import get_upcoming_events, get_user_event_roles_by_role_name
  File "/home/aman/open-event-server/app/api/helpers/query.py", line 6, in <module>
    from app.models.event import Event
  File "/home/aman/open-event-server/app/models/event.py", line 19, in <module>
    from app.models.search import sync
  File "/home/aman/open-event-server/app/models/search/sync.py", line 11, in <module>
    from app.models.search.event import SearchableEvent
  File "/home/aman/open-event-server/app/models/search/event.py", line 2, in <module>
    from elasticsearch_dsl import DocType, Integer, Search, Text
ImportError: cannot import name 'DocType'


I looked on internet for the same and this issue seems to be coming from Elastic-search- DSL which can be averted by downgrading. [[LINK](https://github.com/sabricot/django-elasticsearch-dsl/issues/119)]

**Comment by amansheaven** [comment]
sure sir, I just wanted to shall I downgrade to get this DocType issue resolved??

**Comment by iamareebjamal** [comment]
Fetch latest code and install requirements again. It'll be fixed

**Comment by jhasaurabh312** [comment]
Is this issue still not resolved? If it is open can i take it @iamareebjamal

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by mishra-tanay** [comment]
Is this Issue still open ?

**Comment by iamareebjamal** [comment]
Green means open. Red means closed

**Comment by diru1100** [comment]
Can I work on this?

**Comment by iamareebjamal** [comment]
Yes

**Comment by imrahul361** [comment]
@iamareebjamal I am newbie i don't know what exactly we need to do?Can you help me out?

**Comment by codedsun** [comment]
@imrahul361 - Please read about py.test here https://docs.pytest.org/en/latest/

**Comment by diru1100** [comment]
Hello, 
Do I just have to change the commands from nose to pytest and do the same in necessary documents?
P.S:  pytest command is working fine for all the current tests written when I run it locally.

**Comment by iamareebjamal** [comment]
No, you need to change the test style

**Comment by diru1100** [comment]
> No, you need to change the test style

By style, you mean to change the current tests code to a pytest version of them? 
I have google how to convert from nose to pytest and found [this issue as a reference.](https://github.com/ckan/ckan/issues/3310) [The respective PR for the same](https://github.com/ckan/ckan/pull/4996) was also successfully merged.

**Comment by iamareebjamal** [comment]
Yes

**Comment by diru1100** [comment]
Hello, 
I have made a change to my fork. Once can you please check it out.
https://github.com/diru1100/open-event-server/commit/c9569593b3f81d87d8129661e9fb864b397b0ef2

**Comment by iamareebjamal** [comment]
Send a PR

**Comment by Muzammil7786** [comment]
hi @iamareebjamal  if its not resolved can i take it

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by webmaster-sys** [comment]
hi @iamareebjamal if its not resolved can i take it

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by wanderrful** [comment]
Found this while searching for `help-wanted` tags.

Please correct me if I'm wrong here, but doesn't Pytest prefer having all tests in one giant `tests/` folder? I don't think that the `conftest.py` file will auto-apply itself to all of the subfolders, and I don't think Pytest's CLI has an option for recursively discovering tests in sub-folders.  Maybe I just don't see the option.

In practice, I usually see all tests contained in a single folder as just very many `.py` files.

I noticed that you guys have `integration` and `unit` folders. If you go the route of merging all tests under a single folder, you'll probably want to use markers like `@pytest.mark.integration` and `@pytest.mark.unit` so that you can distinguish them for testing (i.e. `pytest -v tests -m "not integration"` or `pytest -v tests -m "unit"`).

Do you think that merging all of the test files into a single `tests` folder is the right way to go here?

**Comment by iamareebjamal** [comment]
That's not true. We already have pytest setup now, we just want existing classic python tests to be converted to pytest format. It supports nesting directories just fine and we are currently using pytest runner only

**Comment by iamareebjamal** [comment]
We are running the same command as written in README
https://github.com/fossasia/open-event-server/blob/98a7563f8e77043c1b7a467f68023c05da3713c3/.travis.yml#L32
https://travis-ci.com/github/fossasia/open-event-server/builds/185249206

**Comment by wanderrful** [comment]
Maybe I just missed something as I was following the directions for getting setup, my mistake

**Comment by Vineet955** [comment]
@iamareebjamal  Can I try on this issue?

**Comment by iamareebjamal** [comment]
Yes

**Comment by SAP-20** [comment]
a newbie in open source.Can I work on this issue??
