### ISSUE TITLE
Pentabarf export not working

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6513]
https://github.com/fossasia/open-event-server/blob/97e94f2ce14d20341253822b5456c93bef590c71/app/api/helpers/pentabarfxml.py#L61-L64

Line 64: `unsupported operand type(s) for -: 'NoneType' and 'NoneType'`

**Comment by PalAditya** [comment]
I would like to help out with this if possible, but I am not sure what is being asked here. Is the bug due to the fact that ```session.ends_at``` and ```session.starts_at``` is sometimes None? In that case a simple if-else or try-except block would suffice.

However, I looked at Session.py, and in Lines 30-31:

https://github.com/fossasia/open-event-server/blob/97e94f2ce14d20341253822b5456c93bef590c71/app/models/session.py#L30-L31

it is indicated that ```Nullable=False```, so a None value should never occur for those two fields. Is this what you wish to be fixed? (The error probably occurs as the __init__ has None by default and somehow the check fails...I haven't explored it in that detail to be able to comment 😅 )

Please clarify whether the source needs to be fixed or whether I should just check if either of those values are None and in that case, set some default?

**Comment by PalAditya** [comment]
That is my question actually: from the schema, I am unclear whether allowing nulls is intentional or not (as there is ```nullable=False```, seems it is unintentional), but could you confirm that whether *Not Null* is the intended behavior or not?
Or, could you kindly point me to a place where the intended behavior is documented?

**Comment by iamareebjamal** [comment]
There can be nulls in starts_at and ends_at. I don't know if it is intended behavior, but there are nulls in the database, so that is what we'll have to work with.

The "intended behavior" is lost when there is a gap between design and implementation, which is true in this case. Since we can't just add arbitrary values where nulls are present, we will assume that nulls are allowed

**Comment by iamareebjamal** [comment]
Fixed in #6533
