### ISSUE TITLE
Merge local installation steps and generic installation steps

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#7160]
Both methods are same and contain conflicting information. We can't maintain both, and hence they should be merged into one

**Comment by Ranjit1312** [comment]
@iamareebjamal 
can I work on this issue?

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by Ranjit1312** [comment]
@iamareebjamal  
https://github.com/fossasia/open-event-server/pull/7174 is my pull request.

**Comment by ludwig2000** [comment]
Is it still Open?

**Comment by pradeeptrain9** [comment]
i want to work on this issue can you assign me

**Comment by joy2306** [comment]
is it still open?

**Comment by AkshatSaraswat03** [comment]
Hey is this issue still open? I would like to work on it.

**Comment by Shiwali735** [comment]
i wanna work on this issue,  can you assign me please?

**Comment by b-thebest** [comment]
Is it still open? I want to work on this

**Comment by Vineet955** [comment]
@iamareebjamal  Can I work on this issue?

**Comment by b-thebest** [comment]
@iamareebjamal I have observed that in local installation it is stated that source code should be there before running given command. In generic also, we need source code or not? because its not mentioned there. One more question is that, local contains different steps for macOS users, so in case of generic installation we should add steps for mac user also?

**Comment by rishabh129** [comment]
@iamareebjamal can i work on this?

**Comment by Shakil-786** [comment]
is it still open? I want to work on it

**Comment by faisalkhandholpur** [comment]
Can i work this issue
